spring:
  application:
    name: ms-cnab
  datasource:
    url : jdbc:h2:file:./data/db
    driverClassName: org.h2.Driver
    username: sa
    password:
    enabled: true
    batch:
      jdbc:
      initilize-schema: always
    sql:
      init:
        mode: always

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://eureka-user:user-wkxwkxt9@${EUREKA_SERVER}:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

mq:
  queues:
    emissao-cartoes: emissao-cartoes